services:
  - type: cron
    name: krxtrends-test
    runtime: python
    schedule: "0 9 * * *"
    buildCommand: "./render-build.sh && pip install -r requirements.txt"
    startCommand: 'export PATH="$PATH:/opt/render/project/.render/chrome/opt/google/chrome" && python main.py'